### ISSUE TITLE
Resumo do escopo dos bancos de dados e suas composições

### ISSUE THREAD

**Issue by IgorEliezer** [OSMBrasil/stable#22]
Este é um resumo do escopo dos bancos de dados e suas composições.

Foi adotado uma abordagem minimalista para começar. Depois poderá ser expandido quando a composição e estilos de endereçamento conforme necessidade.

### Bancos de dados:
- Polígonos dos municípios
- Lista de nomes de ruas
- Eixos de rua por denominação
- Lista de endereços

### Componentes dos bancos de dados:

**Polígono dos municípios:**
- formato: geojson
- geometria: fechada
- dados
  - nome
  - geocódigo IBGE
  - wikidata, pelo qual se obterá os seguintes dados:
    - ano de criação
    - área
    - população

**Lista de nomes de vias:**
- formato: CSV
- dados:
  - nome oficial
  - ato oficial (decreto, lei)
  - possui variantes?

**Eixos de rua por denominação:**
- formato: geojson
- geometria: poligonal
- dados
  - classe viária
  - pavimento
  - iluminação

**Lista de endereços:**
- formato: CSV
- dados:
  - geohash
  - nome da via
  - número de porta
  - complemento distintivo (detalhado em Notas, no reply a seguir)

**Comment by IgorEliezer** [comment]
## Notas

Por objetividade, aqui vão as anotações para deixar o 1º post o mais limpo o possível para servir de guia.

### Esquemas de endereçamento
Há o predomínio de 2 tipos de esquemas: por eixo de via e por compartimentação do território.
1. Eixo de via - é o mais usado, o endereço é vinculado à rua: Rua X, nº 000, Bairro YYY, Município Z. O número é definindo pela distância em metros em relação ao início do eixo da via.
2. Por compartimentação - mais restrito a cidades como Brasília, o endereço é uma subdivisão do território: Asa Norte, Setor X, Superquadra Y, Bloco Z, Apartamento 000.

No caso do "Eixo de via", pode haver uma variante com o uso de marco de quilometragem no lugar de número: Rodovia Presidente Dutra, km 100,5, Bairro X, Município Y. (ver [Proposed features/Addr:milestone](https://wiki.openstreetmap.org/wiki/Proposed_features/Addr:milestone))

### Complemento distintivo
1. Podemos ter casos de duas residências possuírem o mesmo número de porta mas possuem acessos independentes para a via de acesso pública ou privada, como no casos de condomínios.
2. Neste caso costuma-se usar letras ou "Fundos", exemplo: [37 e 37A](https://www.openstreetmap.org/way/720885263).
3. Os cadastros de endereços do IBGE possui uma (e.g. CNEFE) ou mais colunas de complemento, podendo ter letras, número de sala, etc.
4. O OSM possui tags específicas para complemento: [addr:door, addr:unit, addr:floor e addr:block](https://wiki.openstreetmap.org/wiki/Key:addr#Detailed_subkeys). Exemplo: [OSM](https://www.openstreetmap.org/node/5363803975).
5. Se a opção é simplificar, podemos adotar um padrão de numeração alfanumérica compacta usada no cadastro telefônico (algo em que eu trabalhei). Exemplos:
  - 37A (letra A)
  - 37FU (fundos)
  - 37SL (sobreloja)
  - 37CS1 (casa 1)
  - 37SL1 (sala 1)
  - SN (consolidado como sem número)
  - TL (terreno livre que não recebeu número, não é o equivalente de SN)
5. Pode-se também, por questão de facilitar a leitura, separar a parte numérica numa coluna e a parte complementar em outra. Exemplo: 37 ; SL1  ( ; como separador de valor).

---

(demais notas poderão ser adicionadas abaixo)

**Comment by IgorEliezer** [comment]
@ppKrauss você pode comentar se falta algo?

**Comment by ppKrauss** [comment]
Olá @IgorEliezer , gostei da sua sugestão de [**usar o Projects**](https://github.com/OSMBrasil/stable/projects), as tarefas de mão-na-massa mesmo estão sendo definidas lá. 

---

Aqui nas issues descrevemos e discutimos... Discutir também dá trabalho (!), mas  discussão não pode ser considerado tarefa <br/>(exceto em casos muito especiais quando explicitando a discussão como tarefa).

 A sua documentação aqui está bem escrita, mas vai "pro lixo" se não copiar/colar o texto *markdown*  na [documentação](http://addressforall.org/osms/)... Assim que fecharmos a publicação das vias em GeoJSON, em seguida eu reviso a minha parte da documentação e aí incluo uma tarefa para você fazer suas edições direto na documentação.

**Comment by IgorEliezer** [comment]
Complementando [o meu comentário](https://github.com/OSMBrasil/stable/issues/22#issue-571707105), quanto ao porquê da escolha dos dados que comporiam os eixos de ruas:

> **Eixos de rua por denominação:**
> (...)
> dados:
> * classe viária
> * pavimento
> * iluminação

Dados da existência de pavimentação e iluminação são úteis para empresas de logística para estimar custos e riscos, para análise de graus de urbanização em estudos acadêmicos ou técnicos, e para prefeituras e munícipes para avaliação de lançamento de IPTU (conforme escrevi [neste artigo](https://igoreliezer.blogspot.com/2018/06/vamos-falar-de-iptu.html), parágrafo 8).

Talvez num futuro pode-se incluir dados de calçamento (tag: [sidewalk](https://wiki.openstreetmap.org/wiki/Key:sidewalk)).
