### ISSUE TITLE
Municípios de teste e projetos-piloto

### ISSUE THREAD

**Issue by ppKrauss** [OSMBrasil/stable#5]
(texto revisado em [docs/Rationale](https://github.com/OSMBrasil/stable/blob/master/docs/Rationale.md#munic%C3%ADpios-do-projeto-piloto) depois do fechamento)

----

A proposta do repositório *stable* é ambiciosa, afinal são 5570 municípios e armazenaríamos todos em aberto (com formato GeoJSON), e a cada município ou região um coletivo de [curadores dos dados](https://en.wikipedia.org/wiki/Data_curation) faria minimamente o controle de qualidade nas atualizações.

Por hora, todavia, elegeremos apenas alguns município para **teste**, garantindo a amostragem de extremos em termos de área territorial, densidade populacional, etc., e para **projeto piloto**, constituindo minimamente e simulando a realidade do trabalho de uma curadoria.  

## Projeto piloto
Foram eleitos por hora os seguintes municípios, a partir dos quais ficariam exemplificados por completo os vários aspectos do repositório:

* [**Curitiba**](https://github.com/OSMBrasil/stable/blob/master/PR-Curitiba/PR-Curitiba.geojson) (IBGE 4106902);

* [**Jaraguá do Sul**](https://github.com/OSMBrasil/stable/blob/master/SC-JaraguaSul/SC-JaraguaSul.geojson) (IBGE 4208906);

* [**Monteiro Lobato**](https://github.com/OSMBrasil/stable/tree/master/SP-MonteiroLobato) (IBGE 3531704).

## Testando extremos
Com amostragem apenas parcial para testar e/ou exemplificar usos específicos do repositório, sem compromisso com completeza:

* **Altamira** (IBGE 1500602), maior área (~159530 km2);

* **Santa Cruz de Minas** (IBGE 3157336), menor área (~4 km2);

* **São Paulo** (IBGE 3550308), maior densidade populacional.

**Comment by Vilsonck** [comment]
olá, isso aí!

**Comment by etonbortolini** [comment]
Ok

**Comment by ppKrauss** [comment]
> Ok

Olá Everton! Acho que você estava interessado em Curitiba, por favor inclua um post em https://github.com/OSMBrasil/stable/issues/11 que é por hora o quabra-galho para formalizarmos a adesão de novos curadores.
